// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aifwgrznnxfieipftbwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpZndncnpubnhmaWVpcGZ0YndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1OTc4NzMsImV4cCI6MjA1NjE3Mzg3M30.6dm46m8--gvp1dPghcOTBKtryDQkMqa3HgF9WSzSqUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);